const COUNTRY_MAP: Record<string, string> = {
  "United States of America": "USA",
  "United States": "USA",
  "USA": "USA",
  "U.S.A.": "USA",
  "U.S.": "USA",
  "United Kingdom": "UK",
  "UK": "UK",
  "England": "UK",
  "Great Britain": "UK",
  "Japan": "JPN",
  "Brazil": "BRA",
  "France": "FRA",
  "Germany": "GER",
  "West Germany": "GER",
  "East Germany": "GER",
  "Italy": "ITA",
  "Spain": "ESP",
  "Mexico": "MEX",
  "Canada": "CAN",
  "Australia": "AUS",
  "South Korea": "KOR",
  "China": "CHN",
  "India": "IND",
  "Russia": "RUS",
  "Sweden": "SWE",
  "Norway": "NOR",
  "Denmark": "DEN",
  "Finland": "FIN",
  "Netherlands": "NED",
  "Belgium": "BEL",
  "Switzerland": "SUI",
  "Austria": "AUT",
  "Ireland": "IRL",
  "New Zealand": "NZL",
  "Argentina": "ARG",
  "Chile": "CHI",
  "Colombia": "COL",
  "Portugal": "POR",
  "Poland": "POL",
  "Czech Republic": "CZE",
  "Czechoslovakia": "CZE",
  "Hungary": "HUN",
  "Romania": "ROU",
  "Greece": "GRE",
  "Turkey": "TUR",
  "Thailand": "THA",
  "Hong Kong": "HKG",
  "Taiwan": "TWN",
  "South Africa": "ZAF",
  "Egypt": "EGY",
  "Nigeria": "NGA",
  "Iran": "IRN",
  "Israel": "ISR",
  "Iceland": "ISL",
  "Croatia": "CRO",
  "Serbia": "SRB",
  "Bulgaria": "BGR",
  "Ukraine": "UKR",
  "Indonesia": "IDN",
  "Philippines": "PHL",
  "Malaysia": "MYS",
  "Singapore": "SGP",
  "Vietnam": "VNM",
  "Pakistan": "PAK",
  "Bangladesh": "BGD",
  "Saudi Arabia": "SAU",
  "United Arab Emirates": "ARE",
  "Peru": "PER",
  "Venezuela": "VEN",
  "Cuba": "CUB",
  "Puerto Rico": "PRI",
};

export function abbreviateCountry(country: string | null | undefined): string {
  if (!country) return "-";
  return COUNTRY_MAP[country] ?? country;
}
